## **1. Importing Libraries**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv('/content/Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
le=LabelEncoder()
list=['Surname','Geography','Gender']
for i in list:
  df[i]=le.fit_transform(df[i])
df


RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          2       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          2       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
9995       9996    15606229     1999          771          0       1   39   
9996       9997    15569892     1336          516          0       1   35   
9997       9998    15584532     1570          709          0       0   36   
9998       9999    15682355     2345          772          1       1   42   
9999      10000    15628319     2751          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
x=df.iloc[:,:-1]
x

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          2       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          2       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
9995       9996    15606229     1999          771          0       1   39   
9996       9997    15569892     1336          516          0       1   35   
9997       9998    15584532     1570          709          0       0   36   
9998       9999    15682355     2345          772          1       1   42   
9999      10000    15628319     2751          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [8]:
y=df.iloc[:,-1]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

### 2. Logistic Regression Model

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
x_train

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
1572       1573    15725141     2802          716          0       0   44   
6873       6874    15693088     2033          628          0       0   37   
1766       1767    15645543      212          636          0       0   34   
1391       1392    15787835     2456          775          1       0   38   
9444       9445    15781903     2007          581          1       1   41   
...         ...         ...      ...          ...        ...     ...  ...   
399         400    15646372     2078          616          0       0   66   
2678       2679    15767793     1235          819          0       0   38   
4466       4467    15595160     2258          413          2       1   35   
7334       7335    15759133     2704          616          0       1   18   
7907       7908    15688157     2093          683          1       0   39   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
1572       3  109528.28              1          1               0   
6873       9       0.00              2          1               1   
1766       3       0.00              2          1               1   
1391       4  125212.65              2          1               1   
9444       2  127913.71              2          1               1   
...      ...        ...            ...        ...             ...   
399        1  135842.41              1          1               0   
2678      10       0.00              2          1               0   
4466       2       0.00              2          1               1   
7334       6       0.00              2          1               1   
7907       2   47685.47              2          1               1   

      EstimatedSalary  
1572         27341.63  
6873         34689.77  
1766         44756.25  
1391         15795.88  
9444         44205.95  
...               ...  
399         183840.51  
2678         30498.70  
4466         60972.84  
7334         27308.58  
7907         86019.48  

[8000 rows x 13 columns]

In [11]:
x_test

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
7975       7976    15794356     2628          641          1       1   42   
7567       7568    15750545      478          629          0       1   44   
1311       1312    15750497     1589          850          0       0   37   
6123       6124    15714493      925          465          2       0   33   
4688       4689    15669606      537          690          0       1   33   
...         ...         ...      ...          ...        ...     ...  ...   
1030       1031    15681174     2929          730          0       1   39   
9747       9748    15775761     1306          610          1       0   69   
2891       2892    15774224     1942          613          1       0   30   
7760       7761    15641860      311          764          1       1   34   
5271       5272    15567630      340          721          1       1   40   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
7975       3  121765.37              2          1               1   
7567       5       0.00              4          0               0   
1311       7  153147.75              1          1               1   
6123       6       0.00              2          1               1   
4688       5       0.00              2          1               0   
...      ...        ...            ...        ...             ...   
1030       1  116537.60              1          0               0   
9747       5   86038.21              3          0               0   
2891       5  131563.88              2          1               0   
7760       6  108760.27              2          1               0   
5271       6  100275.88              1          1               0   

      EstimatedSalary  
7975        166516.84  
7567        117572.59  
1311        152235.30  
6123         95500.98  
4688        138017.68  
...               ...  
1030        145679.60  
9747        192743.06  
2891        170638.98  
7760        166324.79  
5271        138564.48  

[2000 rows x 13 columns]

In [12]:
y_train

1572    1
6873    0
1766    0
1391    1
9444    0
       ..
399     1
2678    0
4466    0
7334    0
7907    0
Name: Exited, Length: 8000, dtype: int64

In [13]:
y_test

7975    0
7567    1
1311    0
6123    0
4688    0
       ..
1030    0
9747    1
2891    0
7760    1
5271    1
Name: Exited, Length: 2000, dtype: int64

In [14]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [15]:
pred=lr.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,pred)
score

0.7935

### 3. Random Forest Model

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [21]:
pred = classifier.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, pred)
cm

array([[1528,   59],
       [ 256,  157]])

In [24]:
score=accuracy_score(y_test,pred)
score

0.8425

### 4. Gradient Boosting Algorithm

In [28]:
# Import models and utility functions
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_digits

# Setting SEED for reproducibility
SEED = 23

# Importing the dataset
X, y = load_digits(return_X_y=True)

# Splitting dataset
train_X, test_X, train_y, test_y = train_test_split(X, y,
													test_size = 0.25,
													random_state = SEED)

# Instantiate Gradient Boosting Regressor
gbc = GradientBoostingClassifier(n_estimators=300,
								learning_rate=0.05,
								random_state=100,
								max_features=5 )
# Fit to training set
gbc.fit(train_X, train_y)

# Predict on test set
pred_y = gbc.predict(test_X)

# accuracy
acc = accuracy_score(test_y, pred_y)
print("Gradient Boosting Classifier accuracy is : {:.2f}".format(acc))


Gradient Boosting Classifier accuracy is : 0.98
